version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt  # Монтирование директории с сертификатами SSL
      - ./nginx.conf:/etc/nginx/nginx.conf  # Монтирование конфигурационного файла Nginx
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
